import 'package:flutter/widgets.dart';

import '../services/app_settings.dart';

class AppStrings {
  AppStrings._(this._language);

  final AppLanguage _language;

  static AppStrings of(BuildContext context) =>
      AppStrings._(AppSettings.instance.language);

  String get(String key) {
    final english = _translations[AppLanguage.english]![key] ?? key;
    return _translations[_language]?[key] ?? english;
  }
}

extension AppStringsContext on BuildContext {
  String tr(String key) => AppStrings.of(this).get(key);
}

const Map<AppLanguage, Map<String, String>> _translations = {
  AppLanguage.english: {
    'settings': 'Settings',
    'preferences': 'Preferences',
    'language': 'Language',
    'app_theme': 'App Theme',
    'text_size': 'Text Size',
    'safety_tips': 'Safety Tips',
    'tips_visible': 'Visible on dashboard',
    'tips_hidden': 'Hidden',
    'support': 'Support',
    'help_center': 'Help Center',
    'help_subtitle': 'Emergency use and account support.',
    'about': 'About GuardianNode',
    'about_subtitle': 'Cameroon emergency alert app.',
    'sign_out': 'Sign out',
    'sign_out_title': 'Sign out of GuardianNode?',
    'sign_out_message': 'You will need to verify your phone again to return.',
    'cancel': 'Cancel',
    'confirm': 'Sign out',
    'welcome_back': 'Welcome back!',
    'login_continue': 'Login to continue',
    'phone': 'Phone',
    'continue_whatsapp': 'Continue with WhatsApp',
    'create_account': 'Create account',
    'verify_whatsapp': 'Verify with WhatsApp',
    'waiting_whatsapp': 'Waiting on WhatsApp',
    'open_whatsapp': 'Open WhatsApp',
    'check_now': 'I have sent the message - Check now',
    'home': 'Home',
    'current_location': 'Current Location',
    'location_ready': 'Location ready',
    'getting_location': 'Getting your location...',
    'location_permission_needed': 'Location permission needed',
    'location_disabled': 'Location permission disabled. Open settings.',
    'location_services_off': 'Turn on location services',
    'location_retry': 'Could not get location. Tap to retry.',
    'using_last_location': 'Using last known location',
    'enable_location': 'Enable location for emergency alerts',
    'retry': 'Retry',
    'open_settings': 'Open settings',
    'turn_on': 'Turn on',
    'sos': 'SOS',
    'tap_for_help': 'TAP FOR HELP',
    'network_no_internet':
        'No internet connection. Please check your network and try again.',
    'network_unreachable':
        'Could not reach GuardianNode server. Please try again.',
    'session_expired': 'Session expired. Please login again.',
    'general': 'General',
    'location_permissions': 'Location Permissions',
    'location_always': 'Always',
    'location_off_until_enabled': 'Off until you enable it.',
    'notifications': 'Notifications',
    'privacy_data': 'Privacy & Data',
    'privacy_subtitle': 'Review how account and location data are handled.',
    'delete_account': 'Delete account & data',
    'delete_subtitle': 'Open the secure deletion request page and verify ownership.',
    'allow_location': 'Allow location',
    'enable': 'Enable',
    'report_incident': 'Report Incident',
    'describe_emergency': "What's happening?",
    'describe_emergency_hint':
        'Type it however feels natural -- English, French, or Pidgin all work.',
    'immediate_danger_question':
        'Is anyone in immediate danger right now?',
    'send_report': 'Send report',
    'become_helper': 'Become a Community Helper',
    'request_responder_role': 'Request a verified responder role',
  },
  AppLanguage.french: {
    'settings': 'Parametres',
    'preferences': 'Preferences',
    'language': 'Langue',
    'app_theme': 'Theme',
    'text_size': 'Taille du texte',
    'safety_tips': 'Conseils de securite',
    'tips_visible': 'Visibles sur l accueil',
    'tips_hidden': 'Masques',
    'support': 'Assistance',
    'help_center': 'Centre d aide',
    'help_subtitle': 'Urgences et assistance du compte.',
    'about': 'A propos de GuardianNode',
    'about_subtitle': 'Application d alerte d urgence du Cameroun.',
    'sign_out': 'Se deconnecter',
    'sign_out_title': 'Se deconnecter de GuardianNode ?',
    'sign_out_message': 'Vous devrez verifier votre telephone pour revenir.',
    'cancel': 'Annuler',
    'confirm': 'Se deconnecter',
    'welcome_back': 'Bon retour !',
    'login_continue': 'Connectez-vous pour continuer',
    'phone': 'Telephone',
    'continue_whatsapp': 'Continuer avec WhatsApp',
    'create_account': 'Creer un compte',
    'verify_whatsapp': 'Verifier avec WhatsApp',
    'waiting_whatsapp': 'En attente de WhatsApp',
    'open_whatsapp': 'Ouvrir WhatsApp',
    'check_now': 'Message envoye - Verifier maintenant',
    'home': 'Accueil',
    'current_location': 'Position actuelle',
    'location_ready': 'Position prete',
    'getting_location': 'Recherche de votre position...',
    'location_permission_needed': 'Autorisation de localisation requise',
    'location_disabled': 'Localisation desactivee. Ouvrez les parametres.',
    'location_services_off': 'Activez les services de localisation',
    'location_retry': 'Position introuvable. Touchez pour reessayer.',
    'using_last_location': 'Derniere position connue utilisee',
    'enable_location': 'Activez la localisation pour les alertes',
    'retry': 'Reessayer',
    'open_settings': 'Ouvrir les parametres',
    'turn_on': 'Activer',
    'sos': 'SOS',
    'tap_for_help': 'APPUYEZ POUR DE L AIDE',
    'general': 'General',
    'location_permissions': 'Autorisations de localisation',
    'location_always': 'Toujours',
    'location_off_until_enabled': 'Desactivee jusqu a activation.',
    'notifications': 'Notifications',
    'privacy_data': 'Confidentialite et donnees',
    'privacy_subtitle': 'Consultez la gestion de vos donnees.',
    'delete_account': 'Supprimer le compte et les donnees',
    'delete_subtitle': 'Ouvrir la page de suppression securisee.',
    'allow_location': 'Autoriser',
    'enable': 'Activer',
    'report_incident': 'Signaler un incident',
    'describe_emergency': "Que se passe-t-il ?",
    'describe_emergency_hint':
        'Ecrivez comme cela vous vient -- anglais, francais ou pidgin conviennent tous.',
    'immediate_danger_question':
        'Quelqu un est-il en danger immediat maintenant ?',
    'send_report': 'Envoyer le signalement',
    'become_helper': 'Devenir aidant communautaire',
    'request_responder_role': 'Demander un role de repondant verifie',
  },
  AppLanguage.pidgin: {
    'settings': 'Settings',
    'preferences': 'How you want am',
    'language': 'Language',
    'app_theme': 'App colour',
    'text_size': 'Writing size',
    'safety_tips': 'Safety advice',
    'tips_visible': 'E dey show for home',
    'tips_hidden': 'E hide',
    'support': 'Help',
    'help_center': 'Help Center',
    'help_subtitle': 'Emergency and account help.',
    'about': 'About GuardianNode',
    'about_subtitle': 'Cameroon emergency alert app.',
    'sign_out': 'Comot',
    'sign_out_title': 'You want comot for GuardianNode?',
    'sign_out_message': 'You go verify your phone again before you enter.',
    'cancel': 'No',
    'confirm': 'Comot',
    'welcome_back': 'Welcome back!',
    'login_continue': 'Login make you continue',
    'phone': 'Phone',
    'continue_whatsapp': 'Continue with WhatsApp',
    'create_account': 'Create account',
    'verify_whatsapp': 'Verify with WhatsApp',
    'waiting_whatsapp': 'We dey wait for WhatsApp',
    'open_whatsapp': 'Open WhatsApp',
    'check_now': 'I don send am - Check now',
    'home': 'Home',
    'current_location': 'Your location',
    'location_ready': 'Location ready',
    'getting_location': 'We dey find your location...',
    'location_permission_needed': 'Allow location first',
    'location_disabled': 'Location block. Open settings.',
    'location_services_off': 'Turn on location service',
    'location_retry': 'We no fit get location. Tap try again.',
    'using_last_location': 'We dey use your last location',
    'enable_location': 'Turn on location for emergency alert',
    'retry': 'Try again',
    'open_settings': 'Open settings',
    'turn_on': 'Turn on',
    'sos': 'SOS',
    'tap_for_help': 'TAP FOR HELP',
    'general': 'General',
    'location_permissions': 'Location permissions',
    'location_always': 'Everytime',
    'location_off_until_enabled': 'E off until you turn am on.',
    'notifications': 'Notifications',
    'privacy_data': 'Privacy & Data',
    'privacy_subtitle': 'See how we dey use your information.',
    'delete_account': 'Delete account & data',
    'delete_subtitle': 'Open page make you delete details.',
    'allow_location': 'Allow location',
    'enable': 'Enable',
    'report_incident': 'Report Wetin Happen',
    'describe_emergency': "Wetin dey happen?",
    'describe_emergency_hint':
        'Type am as e dey come -- English, French, or Pidgin all dey fine.',
    'immediate_danger_question': 'Anybody dey for immediate danger now now?',
    'send_report': 'Send the report',
    'become_helper': 'Become Community Helper',
    'request_responder_role': 'Ask for verified responder role',
  },
};
